#pragma once

#define PLACEHOLDER L"Dummy text for now"

#define WELCOMETEXT L"Welcome to our world-famous Ace Casino!\nThe best joint around that you can gamble all of your Phake for more and more and more and more! What's that? You think that we use fake currency for prizes? I can assure you, dear customer, that 100% of your earnings will be Real Phake! Ah, I see that you're planning to sign up for our VIP plan! Let me show you where to register..."

#define ABOUT_MENUTEXT L"\t\t            ♠         ♡         ♣         ♢\n\t\t            RealPhake Ace Casino\n\t\t                     Version 1.0\n\t\t            ♤         ♥         ♧         ♦\n\nRealPhake Ace Casino is a personal project made by Red K.\n\nI have not copyrighted anything and I don't plan on charging anyone for this game, so if you paid money for this, I'm sorry but you got ripped off. Everything in this program falls under fair use; no copyrighted material contained in this program belongs to me in any way, it's just for fun and I am not making money off of it.\n\nSpecial Thanks to Professor Seth Reed and The Pentamollis Project.\n\nFeel free to contact me through Discord:\nRed#0681"

#define RPAC_MENUTEXT L"bruh"

#define POKER_MENUTEXT L"Poker is not the simplest game in the casino, but in my opinion is the most entertaining one. Don't be discouraged, however. It shouldn't be that hard to learn the rules.\n--------------------------------------------------------------------------------------------\nThe main objective of Poker is to have the highest quality hand you can pull from a deck of cards. The quality table is as follows:\n     One Pair\n          Two cards with the same number.\n          Hand Ex.: 5, 5, X, X, X.\n          +2 Points.\n     Two Pairs\n          Two of two cards with the same number.\n          Hand Ex.: 5, 5, 8, 8, X.\n          +4 Points.\n     Three of a Kind\n          Three cards with the same number.\n          Hand Ex.: 7, 7, 7, X, X.\n          +6 Points.\n     Straight\n          A hand that has numbers that count in a row.\n          Hand Ex.: 3, 4, 5, 6, 7.\n          +10 Points.\n     Flush\n          A hand comprised of the same suit.\n          Hand Ex.: ♠X, ♠X, ♠X, ♠X, ♠X.\n          +12 Points.\n     Full House\n          A hand made of a One Pair and a Three of a Kind.\n          Hand Ex.: 4, 4, J, J, J.\n          +15 Points.\n     Four of a Kind\n          Four cards with the same number.\n          Hand Ex.: 3, 3, 3, 3, X.\n          +25 Points.\n     Straight Flush\n          A Flush and a Straight combined.\n          Hand Ex.: ♠9, ♠10, ♠J, ♠Q, ♠K.\n          +30 Points.\n     Royal Flush\n          A Flush only containing royal cards. (The aces are not royal cards.)\n          Hand Ex.: ♠J, ♠Q, ♠Q, ♠Q, ♠K.\n          +50 Points.\nIn this specific version of Poker, you will have an opponent who is trying to get a higher quality hand than you. If you and your opponent have the same quality hand, whoever has the higher card value will win the tie. The card value table is as follows:\n\t\t2, 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K, A.\nEvery round, you each get 5 cards that you may (individually) either choose to redraw or keep. Once each person has their final hand, they will reveal their cards. Whoever has the highest quality hand wins that round and will earn the ammount of points associated with the hand that they just won with. Play to 10 rounds and whoever has the most points by the end wins whatever was bet."
